# Generated by Django 4.2.20 on 2025-03-27 09:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название букета')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение букета')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('composition', models.CharField(max_length=100, verbose_name='Состав')),
                ('occasion', models.CharField(choices=[('День рождения', 'День рождения'), ('Свадьба', 'Свадьба'), ('В школу', 'В школу'), ('Без повода', 'Без повода'), ('Другой повод', 'Другой повод')], default='Без повода', max_length=256, verbose_name='Повод')),
                ('color_scheme', models.CharField(choices=[('Без цветовой гаммы', 'Без цветовой гаммы'), ('Красные', 'Красные'), ('Синие', 'Синие')], default='Без цветовой гаммы', max_length=256, verbose_name='Цветовая гамма')),
            ],
            options={
                'verbose_name': 'Букет',
                'verbose_name_plural': 'Букеты',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='Внешний ID покупателя')),
                ('tg_username', models.CharField(blank=True, max_length=50, verbose_name='Имя покупателя в Telegram')),
                ('first_name', models.CharField(blank=True, max_length=5, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=256, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('home_address', models.CharField(blank=True, max_length=50, verbose_name='Адрес доставки')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=256, verbose_name='Имя покупателя')),
                ('customer_chat_id', models.CharField(blank=True, max_length=256, verbose_name='Chat ID покупателя')),
                ('order_price', models.PositiveIntegerField(verbose_name='Цена заказа')),
                ('order_status', models.CharField(choices=[('Заявка обрабатывается', 'Заявка обрабатывается'), ('Собираем ваш букет', 'Собираем ваш букет'), ('Букет в пути', 'Букет в пути'), ('Букет у вас', 'Букет у вас')], default='Заявка обрабатывается', max_length=256, verbose_name='Статус заказа')),
                ('comments', models.CharField(blank=True, max_length=256, verbose_name='Комментарии')),
                ('delivery_address', models.CharField(default=' ', max_length=256, verbose_name='Адрес доставки')),
                ('delivery_date', models.CharField(blank=True, max_length=30, verbose_name='Дата доставки')),
                ('delivery_time', models.CharField(blank=True, max_length=30, verbose_name='Время доставки')),
                ('flower_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='FlowerShop.bouquet', verbose_name='Название букета')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
